name: naserca dot com
markdown: redcarpet
pygments: true
exclude: [Rakefile, README.md, Gemfile, Gemfile.lock]
assets: 
  debug: true
  cachebust: hard
  gzip: false
  sources:
    - _assets
    - _assets/scripts
    - _assets/stylesheets